### ISSUE TITLE
I'm not sure #2

### ISSUE THREAD

**Issue by chickencoder** [crossroadchurch/paul#3]
Traceback (most recent call last):
  File "C:\Users\CCF Youth\Desktop\paul-master\openlp\core\ui\servicemanager.py", line 1507, in remote_edit
    self.add_service_item(new_item, replace=True)
  File "C:\Users\CCF Youth\Desktop\paul-master\openlp\core\ui\servicemanager.py", line 1407, in add_service_item
    item.merge(self.service_items[s_item]['service_item'])
  File "C:\Users\CCF Youth\Desktop\paul-master\openlp\core\lib\serviceitem.py", line 631, in merge
    self.render()
  File "C:\Users\CCF Youth\Desktop\paul-master\openlp\core\lib\serviceitem.py", line 325, in render
    xml_lines = self.extra_data_dict[verse_tag.lower()]
KeyError: 'v3'

**Comment by chickencoder** [comment]
Happened when inserting several [br] tags into an old hymn and wouldn't then save the newly-edited version.
